# Generated by Django 6.0.4 on 2026-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.FileField(upload_to="cursos_escola/"),
        ),
    ]
