# Generated by Django 6.0.4 on 2026-04-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("soft_skill", "Soft Skill"),
                            ("tecnologia", "Tecnologia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("propinas", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cadeiras", models.IntegerField()),
                ("objetivos", models.TextField()),
                ("diretor", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="making_of/")),
                ("decisoes", models.TextField()),
                ("erros_correcoes", models.TextField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_conclusao", models.DateField()),
                ("link_certificado", models.URLField(blank=True)),
                ("descricao", models.TextField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        related_name="formacoes", to="portfolio.licenciatura"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link", models.URLField(blank=True)),
                ("rating", models.IntegerField(default=0)),
                ("descricao", models.TextField()),
                ("aspetos_relevantes", models.TextField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tecnologias",
                        to="portfolio.competencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("orientador", models.CharField(max_length=100)),
                ("link_pdf", models.URLField()),
                ("descricao", models.TextField()),
                ("rating", models.IntegerField(default=0)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("programa", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="uc_images/"),
                ),
                (
                    "docentes",
                    models.TextField(
                        help_text="Link para a página pessoal da Lusófona"
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("descricao", models.TextField()),
                ("link_github", models.URLField(blank=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voluntariado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data", models.DateField()),
                ("descricao", models.TextField()),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        related_name="voluntariados", to="portfolio.competencia"
                    ),
                ),
            ],
        ),
    ]
