# Generated by Django 6.0.4 on 2026-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenciatura",
            old_name="cadeiras",
            new_name="ano_inicio",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="propinas",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="ano_fim",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="grau",
            field=models.CharField(default="Licenciatura", max_length=100),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="instituicao",
            field=models.CharField(default="Universidade Lusófona", max_length=200),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="logotipo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
