# Generated by Django 6.0.4 on 2026-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_cadeiras_licenciatura_ano_inicio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("soft_skill", "Soft Skill"),
                    ("tecnologia", "Tecnologia"),
                    ("hard_skill", "Hard Skill"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="logotipo",
            field=models.FileField(
                blank=True, null=True, upload_to="logos_licenciatura/"
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="imagem",
            field=models.FileField(upload_to="making_of/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.FileField(blank=True, null=True, upload_to="projetos_img/"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="tecnologias/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.FileField(blank=True, null=True, upload_to="uc_images/"),
        ),
    ]
