# Generated by Django 6.0.4 on 2026-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_alter_competencia_tipo_alter_licenciatura_logotipo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voluntariado",
            name="data",
        ),
        migrations.AddField(
            model_name="voluntariado",
            name="data_conclusao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voluntariado",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
