# Generated by Django 6.0.4 on 2026-04-25 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_remove_voluntariado_data_voluntariado_data_conclusao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="nome",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="unidades_curriculares",
            field=models.ManyToManyField(
                blank=True, related_name="tecnologias", to="portfolio.unidadecurricular"
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
