# Generated by Django 6.0.4 on 2026-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_makingof_nome_tecnologia_unidades_curriculares_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="imagem",
            field=models.FileField(blank=True, null=True, upload_to="making_of/"),
        ),
    ]
